# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Modify your HTML files to include environment variables
      - name: Inject environment variables
        run: |
          # Create a script with environment variables in your HTML files
          for file in *.html; do
            if [ -f "$file" ]; then
              # Create temp file
              temp_file=$(mktemp)
              # Add environment variables before the closing </head> tag
              awk '
                /<\/head>/ {
                  print "<script id=\"env-variables\" type=\"application/json\">"
                  print "{"
                  print "  \"FIREBASE_API_KEY\": \"${{ secrets.FIREBASE_API_KEY }}\","
                  print "  \"FIREBASE_AUTH_DOMAIN\": \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\","
                  print "  \"FIREBASE_PROJECT_ID\": \"${{ secrets.FIREBASE_PROJECT_ID }}\","
                  print "  \"FIREBASE_STORAGE_BUCKET\": \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\","
                  print "  \"FIREBASE_MESSAGING_SENDER_ID\": \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\","
                  print "  \"FIREBASE_APP_ID\": \"${{ secrets.FIREBASE_APP_ID }}\","
                  print "  \"AWS_S3_BUCKET\": \"${{ secrets.AWS_S3_BUCKET || '\''maclellanfamily.com'\''}}\","
                  print "  \"AWS_S3_REGION\": \"${{ secrets.AWS_S3_REGION || '\''us-east-2'\''}}\","
                  print "  \"AWS_BASE_FOLDER\": \"${{ secrets.AWS_BASE_FOLDER || '\''0 US'\''}}\","
                  print "  \"AWS_ACCESS_KEY_ID\": \"${{ secrets.AWS_ACCESS_KEY_ID }}\","
                  print "  \"AWS_SECRET_ACCESS_KEY\": \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\","
                  print "  \"URL_EXPIRATION\": \"${{ secrets.URL_EXPIRATION || '\''3600'\''}}\""
                  print "}"
                  print "</script>"
                }
                { print }
              ' "$file" > "$temp_file"
              mv "$temp_file" "$file"
            fi
          done

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4