name: Jekyll Build with Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Create _config.yml with secrets
      run: |
        cat > _config.yml <<EOL
        # Site settings
        firebase_config:
          apiKey: ${{ secrets.FIREBASE_API_KEY }}
          authDomain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          storageBucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          messagingSenderId: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          appId: ${{ secrets.FIREBASE_APP_ID }}

        aws_config:
          accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_S3_REGION || 'us-east-2' }}
          bucket: ${{ secrets.AWS_S3_BUCKET || 'maclellanfamily.com' }}
          baseFolder: ${{ secrets.AWS_BASE_FOLDER || '0 US' }}
          urlExpiration: ${{ secrets.URL_EXPIRATION || '3600' }}
        EOL

    - name: Create environment.js
      run: |
        mkdir -p assets/js
        cat > assets/js/environment.js <<EOL
        const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
        };

        const awsConfig = {
            accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}",
            secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
            region: "${{ secrets.AWS_S3_REGION || 'us-east-2' }}",
            bucket: "${{ secrets.AWS_S3_BUCKET || 'maclellanfamily.com' }}",
            baseFolder: "${{ secrets.AWS_BASE_FOLDER || '0 US' }}",
            urlExpiration: ${{ secrets.URL_EXPIRATION || 3600 }}
        };
        EOL

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site