name: Jekyll Build with Secrets

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Create _config.yml with secrets
      run: |
        cat > _config.yml <<EOL
        # Site settings
        title: Your Site Title
        description: Your site description
        
        # Build settings
        markdown: kramdown
        
        # Environment variables
        firebase_config:
          apiKey: ${{ secrets.FIREBASE_API_KEY }}
          authDomain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          storageBucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          messagingSenderId: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          appId: ${{ secrets.FIREBASE_APP_ID }}

        aws_config:
          accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_S3_REGION || 'us-east-2' }}
          bucket: ${{ secrets.AWS_S3_BUCKET || 'maclellanfamily.com' }}
          baseFolder: ${{ secrets.AWS_BASE_FOLDER || '0 US' }}
          urlExpiration: ${{ secrets.URL_EXPIRATION || '3600' }}
        EOL

    - name: Create environment.js
      run: |
        mkdir -p assets/js
        cat > assets/js/environment.js <<EOL
        const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
        };

        const awsConfig = {
            accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}",
            secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
            region: "${{ secrets.AWS_S3_REGION || 'us-east-2' }}",
            bucket: "${{ secrets.AWS_S3_BUCKET || 'maclellanfamily.com' }}",
            baseFolder: "${{ secrets.AWS_BASE_FOLDER || '0 US' }}",
            urlExpiration: ${{ secrets.URL_EXPIRATION || 3600 }}
        };
        EOL

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4